### ISSUE TITLE
fbuild error

### ISSUE THREAD

**Issue by addeps3** [kirbyfan64/uterm#1]
Very sorry if this isn't your  business, but any idea why this is happening? (running fbuild inside directory with fbuildroot.py)
```
$ fbuild
Traceback (most recent call last):
  File "/usr/bin/fbuild", line 11, in <module>
    load_entry_point('fbuild==0.2', 'console_scripts', 'fbuild')()
  File "/usr/lib/python3.6/site-packages/fbuild-0.2-py3.6.egg/fbuild/main.py", line 164, in main
    raise fbuildroot
  File "/usr/lib/python3.6/site-packages/fbuild-0.2-py3.6.egg/fbuild/main.py", line 19, in <module>
    import fbuildroot
  File "/home/user/git/uterm/fbuildroot.py", line 3, in <module>
    from fbuild.builders.cxx import guess
ImportError: cannot import name 'guess'

```

**Comment by kirbyfan64** [comment]
- This build script requires the fbuild version from the `dev` branch.
- I don't think you'll be able to build this right now, because the build script is a hot flaming crapfest... I'll probably get around to fixing up the issues over this weekend...

**Comment by kirbyfan64** [comment]
@addeps3 The build system should be 100% functional now! It took a lot longer for me to get around to fixing it than I thought, but hey, as long as it works, right? :wink:
